### ISSUE TITLE
about your dataset

### ISSUE THREAD

**Issue by Thunder-z** [HirotetsuHongo/smd-detection#1]
Hi!
does SMD means Singapore Marine Dataset in your repo?

**Comment by HirotetsuHongo** [comment]
No. This repository is for detection SMD neurons of C. elegans, one of namatodes. SMD is a name of the neuron.

**Comment by Thunder-z** [comment]
> No. This repository is for detection SMD neurons of C. elegans, one of namatodes. SMD is a name of the neuron.

thank you for your reply!
